.nh
.TH "Armv8-A" "7" "" "" "arm man man"  

.SS Arm Version
 8

.SS Arm Architecture Profile
 A, Application

.SS Arm specification xml Version
 86A

.SS Arm8-A A32/T32 Instruction Set Index
 man arm32

.SS Arm8-A A32/T32 instruction man prefix
 arm32-

.SS Arm8-A A64 Instruction Set Index
 man arm64

.SS Arm8-A A64 instruction man prefix
 arm64-

.SS Arm8-A Examples 
