.nh
.TH "PACIA, PACIA1716, PACIASP, PACIAZ, PACIZA -- A64" "7" " "  "instruction" "system"
.SS PACIA, PACIA1716, PACIASP, PACIAZ, PACIZA
 Pointer Authentication Code for Instruction address, using key A

 Pointer Authentication Code for Instruction address, using key A. This
 instruction computes and inserts a pointer authentication code for an
 instruction address, using a modifier and key A.

 The address is:

 In the general-purpose register that is specified by <Xd> for PACIA and PACIZA.

 In the general-purpose register that is specified by <Xd> for PACIA and PACIZA.

 In the general-purpose register that is specified by <Xd> for PACIA and PACIZA.

 In X17, for PACIA1716.

 In X30, for PACIASP and PACIAZ.

 In X30, for PACIASP and PACIAZ.


 The modifier is:

 In the general-purpose register or stack pointer that is specified by <Xn|SP>
 for PACIA.

 In the general-purpose register or stack pointer that is specified by <Xn|SP>
 for PACIA.

 The value zero, for PACIZA and PACIAZ.

 The value zero, for PACIZA and PACIAZ.

 In X16, for PACIA1716.

 In SP, for PACIASP.



It has encodings from 2 classes: Integer and System

.SS Integer - A64 - general
 
                                       13                          
       29                            14 |                          
     30 |                          15 | |                          
   31 | |              21        16 | | |    10         5         0
    | | |               |         | | | |     |         |         |
  |1|1|0|1 1 0 1 0 1 1 0|0 0 0 0 1|0|0|.|0 0 0|. . . . .|. . . . .|
  |   |                 |         | | | |     |         |
  |   `-S               `-opcode2 | | | |     `-Rn      `-Rd
  `-sf                            | | | `-opcode[2:0]
                                  | | `-Z
                                  | `-opcode[4]
                                  `-opcode[5]
  
  
 
.SS PACIA(Z == 0)
 
 PACIA  <Xd>, <Xn|SP>
.SS PACIZA(Z == 1 && Rn == 11111)
 
 PACIZA  <Xd>
 
 boolean source_is_sp = FALSE;
 integer d = UInt(Rd);
 integer n = UInt(Rn);
 
 if !HavePACExt() then
     UNDEFINED;
 
 if Z == '0' then // PACIA
     if n == 31 then source_is_sp = TRUE;
 else // PACIZA
     if n != 31 then UNDEFINED;
.SS System - A64
 
                                                                   
                                                                   
                       21                                          
                     22 |  19    16      12       8     5         0
                      | |   |     |       |       |     |         |
   1 1 0 1 0 1 0 1 0 0|0|0 0|0 1 1|0 0 1 0|0 0 x 1|0 0 x|1 1 1 1 1|
                      | |   |     |       |       |     |
                      | |   `-op1 `-CRn   `-CRm   `-op2 `-Rt
                      | `-op0
                      `-L
  
  
 
.SS PACIA1716(CRm == 0001 && op2 == 000)
 
 PACIA1716
.SS PACIASP(CRm == 0011 && op2 == 001)
 
 PACIASP
.SS PACIAZ(CRm == 0011 && op2 == 000)
 
 PACIAZ
 
 integer d;
 integer n;
 boolean source_is_sp = FALSE;
 
 case CRm:op2 of
     when '0011 000' // PACIAZ 
         d = 30;
         n = 31;
     when '0011 001' // PACIASP
         d = 30;
         source_is_sp = TRUE;
         if HaveBTIExt() then
             // Check for branch target compatibility between PSTATE.BTYPE
             // and implicit branch target of PACIASP instruction.
             SetBTypeCompatible(BTypeCompatible_PACIXSP());
 
     when '0001 000' // PACIA1716
         d = 17;
         n = 16;
     when '0001 010' SEE "PACIB";
     when '0001 100' SEE "AUTIA";
     when '0001 110' SEE "AUTIB";
     when '0011 01x' SEE "PACIB";
     when '0011 10x' SEE "AUTIA";
     when '0011 11x' SEE "AUTIB";
     when '0000 111' SEE "XPACLRI";
     otherwise       SEE "HINT";
 
 if HavePACExt() then
     if source_is_sp then
         X[d] = AddPACIA(X[d], SP[]);
     else
         X[d] = AddPACIA(X[d], X[n]);
 

.SS Assembler Symbols

 <Xd>
  Encoded in Rd
  Is the 64-bit name of the general-purpose destination register, encoded in the
  "Rd" field.

 <Xn|SP>
  Encoded in Rn
  Is the 64-bit name of the general-purpose source register or stack pointer,
  encoded in the "Rn" field.



.SS Operation

 if HavePACExt() then
     if source_is_sp then
         X[d] = AddPACIA(X[d], SP[]);
     else
         X[d] = AddPACIA(X[d], X[n]);

