.nh
.TH "BL -- A64" "7" " "  "instruction" "general"
.SS BL
 Branch with Link

 Branch with Link branches to a PC-relative offset, setting the register X30 to
 PC+4. It provides a hint that this is a subroutine call.



.SS 26-bit signed PC-relative branch offset - A64 - BL_only_branch_imm
 
                                                                   
                                                                   
                                                                   
   31        26                                                   0
    |         |                                                   |
  |1|0 0 1 0 1|. . . . . . . . . . . . . . . . . . . . . . . . . .|
  |           |
  `-op        `-imm26
  
  
 
.SS 26-bit signed PC-relative branch offset
 
 BL  <label>
 
 BranchType branch_type = if op == '1' then BranchType_DIRCALL else BranchType_DIR;
 bits(64) offset = SignExtend(imm26:'00', 64);
 
 if branch_type == BranchType_DIRCALL then X[30] = PC[] + 4;
 
 BranchTo(PC[] + offset, branch_type);
 

.SS Assembler Symbols

 <label>
  Encoded in imm26
  Is the program label to be unconditionally branched to. Its offset from the
  address of this instruction, in the range +/-128MB, is encoded as "imm26"
  times 4.



.SS Operation

 if branch_type == BranchType_DIRCALL then X[30] = PC[] + 4;
 
 BranchTo(PC[] + offset, branch_type);

