.nh
.TH "MUL -- A64" "7" " "  "alias" "general"
.SS MUL
 MUL is an alias of MADD

 Multiply



.SS Integer - A64 - general
 
                                                                   
                                                                   
                                   15                              
   31  29        24    21        16 |        10         5         0
    |   |         |     |         | |         |         |         |
  |.|0 0|1 1 0 1 1|0 0 0|. . . . .|0|1 1 1 1 1|. . . . .|. . . . .|
  | |             |     |         | |         |         |
  | `-op54        |     `-Rm      | `-Ra      `-Rn      `-Rd
  `-sf            `-op31          `-o0
  
  
 
.SS 32-bit(sf == 0)
 
 MUL  <Wd>, <Wn>, <Wm>
 
 MADD <Wd>, <Wn>, <Wm>, WZR
.SS 64-bit(sf == 1)
 
 MUL  <Xd>, <Xn>, <Xm>
 
 MADD <Xd>, <Xn>, <Xm>, XZR
 

.SS Assembler Symbols

 <Wd>
  Encoded in Rd
  Is the 32-bit name of the general-purpose destination register, encoded in the
  "Rd" field.

 <Wn>
  Encoded in Rn
  Is the 32-bit name of the first general-purpose source register holding the
  multiplicand, encoded in the "Rn" field.

 <Wm>
  Encoded in Rm
  Is the 32-bit name of the second general-purpose source register holding the
  multiplier, encoded in the "Rm" field.

 <Xd>
  Encoded in Rd
  Is the 64-bit name of the general-purpose destination register, encoded in the
  "Rd" field.

 <Xn>
  Encoded in Rn
  Is the 64-bit name of the first general-purpose source register holding the
  multiplicand, encoded in the "Rn" field.

 <Xm>
  Encoded in Rm
  Is the 64-bit name of the second general-purpose source register holding the
  multiplier, encoded in the "Rm" field.



.SS Operation

 The manual of MADD gives pseudocode for MUL.
