.nh
.TH "STCLRB, STCLRLB -- A64" "7" " "  "alias" "general"
.SS STCLRB, STCLRLB
 STCLRLB is an alias of LDCLRLB

 Atomic bit clear on byte in memory, without return

 Atomic bit clear on byte in memory, without return, atomically loads an 8-bit
 byte from memory, performs a bitwise AND with the complement of the value held
 in a register on it, and stores the result back to memory.

 STCLRB has no memory ordering semantics.

 STCLRLB stores to memory with release semantics, as described in Load-Acquire,
 Store-Release.

 STCLRLB stores to memory with release semantics, as described in Load-Acquire,
 Store-Release.


 For information about memory accesses see Load/Store addressing modes.



.SS Integer - A64 - general
 
                       21                                          
                     22 |                                          
             26    23 | |          15                              
     30    27 |  24 | | |        16 |    12  10         5         0
      |     | |   | | | |         | |     |   |         |         |
  |0 0|1 1 1|0|0 0|0|.|1|. . . . .|0|0 0 1|0 0|. . . . .|1 1 1 1 1|
  |         |     | |   |         | |         |         |
  `-size    `-V   | `-R `-Rs      | `-opc     `-Rn      `-Rt
                  `-A             `-o3
  
  
 
.SS No memory ordering(R == 0)
 
 STCLRB  <Ws>, [<Xn|SP>]
 
 LDCLRB <Ws>, WZR, [<Xn|SP>]
.SS Release(R == 1)
 
 STCLRLB  <Ws>, [<Xn|SP>]
 
 LDCLRLB <Ws>, WZR, [<Xn|SP>]
 

.SS Assembler Symbols

 <Ws>
  Encoded in Rs
  Is the 32-bit name of the general-purpose register holding the data value to
  be operated on with the contents of the memory location, encoded in the "Rs"
  field.

 <Xn|SP>
  Encoded in Rn
  Is the 64-bit name of the general-purpose base register or stack pointer,
  encoded in the "Rn" field.



.SS Operation

 The manual of LDCLRLB gives pseudocode for STCLRLB.

.SS Operational Notes

 
 If PSTATE.DIT is 1, the timing of this instruction is insensitive to the value of the data being loaded or stored.
