.nh
.TH "ADR -- AArch32" "7" " "  "instruction" "general"
.SS ADR
 Form PC-relative address

 Form PC-relative address adds an immediate value to the PC value to form a PC-
 relative address, and writes the result to the destination register.

 For more information about the constrained unpredictable behavior, see
 Architectural Constraints on UNPREDICTABLE behaviors.


It has encodings from the following instruction sets:  A32 (A1 and A2) and  T32 (T1, T2 and T3).

.SS A1 - A32
 
                                                                   
                                                                   
                         20                                        
         28      24    21 |      16      12                       0
          |       |     | |       |       |                       |
  |. . . .|0 0 1 0|1 0 0|0|1 1 1 1|. . . .|. . . . . . . . . . . .|
  |               |     | |       |       |
  `-cond(!= 1111) `-opc | `-Rn    `-Rd    `-imm12
                        `-S
  
  
 
.SS A1
 
 ADR{<c>}{<q>} <Rd>, <label>
 
 d = UInt(Rd);  imm32 = A32ExpandImm(imm12);  add = TRUE;
.SS A2 - A32
 
                                                                   
                                                                   
                         20                                        
         28      24    21 |      16      12                       0
          |       |     | |       |       |                       |
  |. . . .|0 0 1 0|0 1 0|0|1 1 1 1|. . . .|. . . . . . . . . . . .|
  |               |     | |       |       |
  `-cond(!= 1111) `-opc | `-Rn    `-Rd    `-imm12
                        `-S
  
  
 
.SS A2
 
 ADR{<c>}{<q>} <Rd>, <label>
 
 d = UInt(Rd);  imm32 = A32ExpandImm(imm12);  add = FALSE;
.SS T1 - T32
 
                                                                   
                                                                   
           11                                                      
         12 |     8               0                                
          | |     |               |                                
   1 0 1 0|0|. . .|. . . . . . . .|                                
          | |     |
          | `-Rd  `-imm8
          `-SP
  
  
 
.SS T1
 
 ADR{<c>}{<q>} <Rd>, <label>
 
 d = UInt(Rd);  imm32 = ZeroExtend(imm8:'00', 32);  add = TRUE;
.SS T2 - T32
 
                       06                                          
                     07 |                                          
             11    08 | |          15                              
           12 |  09 | | |05      01 |    12       8               0
            | |   | | | | |       | |     |       |               |
   1 1 1 1 0|.|1 0|1|0|1|0|1 1 1 1|0|. . .|. . . .|. . . . . . . .|
            |     |   |   |         |     |       |
            `-i   |   |   `-Rn      |     `-Rd    `-imm8
                  |   `-o2          `-imm3
                  `-o1
  
  
 
.SS T2
 
 ADR{<c>}{<q>} <Rd>, <label>
 
 d = UInt(Rd);  imm32 = ZeroExtend(i:imm3:imm8, 32);  add = FALSE;
 if d == 15 then UNPREDICTABLE;     // Armv8-A removes UNPREDICTABLE for R13
.SS T3 - T32
 
                       06                                          
                     07 |                                          
             11    08 | |          15                              
           12 |  09 | | |05      01 |    12       8               0
            | |   | | | | |       | |     |       |               |
   1 1 1 1 0|.|1 0|0|0|0|0|1 1 1 1|0|. . .|. . . .|. . . . . . . .|
            |     |   |   |         |     |       |
            `-i   |   |   `-Rn      |     `-Rd    `-imm8
                  |   `-o2          `-imm3
                  `-o1
  
  
 
.SS T3
 
 ADR{<c>}.W <Rd>, <label>
 
 ADR{<c>}{<q>} <Rd>, <label>
 
 d = UInt(Rd);  imm32 = ZeroExtend(i:imm3:imm8, 32);  add = TRUE;
 if d == 15 then UNPREDICTABLE;   // Armv8-A removes UNPREDICTABLE for R13
 
 if ConditionPassed() then
     EncodingSpecificOperations();
     result = if add then (Align(PC,4) + imm32) else (Align(PC,4) - imm32);
     if d == 15 then          // Can only occur for A32 encodings
         ALUWritePC(result);
     else
         R[d] = result;
 

.SS Assembler Symbols

 <c>
  See Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <Rd>
  Encoded in Rd
  For encoding A1 and A2: is the general-purpose destination register, encoded
  in the "Rd" field. If the PC is used, the instruction is a branch to the
  address calculated by the operation. This is an interworking branch, see
  Pseudocode description of operations on the AArch32 general-purpose registers
  and the PC.

 <Rd>
  Encoded in Rd
  For encoding T1, T2 and T3: is the general-purpose destination register,
  encoded in the "Rd" field.

 <label>
  Encoded in imm12
  For encoding A1 and A2: the label of an instruction or literal data item whose
  address is to be loaded into <Rd>. The assembler calculates the required value
  of the offset from the Align(PC, 4) value of the ADR instruction to this
  label.           If the offset is zero or positive, encoding A1 is used, with
  imm32 equal to the offset.           If the offset is negative, encoding A2 is
  used, with imm32 equal to the size of the offset. That is, the use of encoding
  A2 indicates that the required offset is minus the value of imm32.
  Permitted values of the size of the offset are any of the constants described
  in Modified immediate constants in A32 instructions.

 <label>
  Encoded in imm8
  For encoding T1: the label of an instruction or literal data item whose
  address is to be loaded into <Rd>. The assembler calculates the required value
  of the offset from the Align(PC, 4) value of the ADR instruction to this
  label. Permitted values of the size of the offset are multiples of 4 in the
  range 0 to 1020.

 <label>
  Encoded in i:imm3:imm8
  For encoding T2 and T3: the label of an instruction or literal data item whose
  address is to be loaded into <Rd>. The assembler calculates the required value
  of the offset from the Align(PC, 4) value of the ADR instruction to this
  label.           If the offset is zero or positive, encoding T3 is used, with
  imm32 equal to the offset.           If the offset is negative, encoding T2 is
  used, with imm32 equal to the size of the offset. That is, the use of encoding
  T2 indicates that the required offset is minus the value of imm32.
  Permitted values of the size of the offset are 0-4095.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();
     result = if add then (Align(PC,4) + imm32) else (Align(PC,4) - imm32);
     if d == 15 then          // Can only occur for A32 encodings
         ALUWritePC(result);
     else
         R[d] = result;

