.nh
.TH "LDAEX -- AArch32" "7" " "  "instruction" "general"
.SS LDAEX
 Load-Acquire Exclusive Word

 Load-Acquire Exclusive Word loads a word from memory, writes it to a register
 and:


 The instruction also has memory ordering semantics as described in Load-
 Acquire, Store-Release.

 For more information about support for shared memory see Synchronization and
 semaphores. For information about memory accesses see Memory accesses.

 For more information about the constrained unpredictable behavior of this
 instruction, see Architectural Constraints on UNPREDICTABLE behaviors.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                                                   
                                             10                    
                         20                11 |                    
         28        23  21 |      16      12 | | 9 8       4       0
          |         |   | |       |       | | | | |       |       |
  |. . . .|0 0 0 1 1|0 0|1|. . . .|. . . .|1|1|1|0|1 0 0 1|1 1 1 1|
  |                 |   | |       |           | |         |
  `-cond(!= 1111)   |   | `-Rn    `-Rt        | `-ord     `-xRt
                    |   `-L                   `-ex
                    `-size
  
  
 
.SS A1
 
 LDAEX{<c>}{<q>} <Rt>, [<Rn>]
 
 t = UInt(Rt);  n = UInt(Rn);
 if t == 15 || n == 15 then UNPREDICTABLE;
.SS T1 - T32
 
                                                                   
                                                                   
                         05                                        
                       06 |      01      12       8 7 6   4       0
                        | |       |       |       | | |   |       |
   1 1 1 0 1 0 0 0 1 1 0|1|. . . .|. . . .|1 1 1 1|1|1|1 0|1 1 1 1|
                        | |       |       |         | |   |
                        | `-Rn    `-Rt    `-Rt2     | |   `-Rd
                        `-L                         | `-sz
                                                    `-op
  
  
 
.SS T1
 
 LDAEX{<c>}{<q>} <Rt>, [<Rn>]
 
 t = UInt(Rt);  n = UInt(Rn);
 if t == 15 || n == 15 then UNPREDICTABLE;
 
 if ConditionPassed() then
     EncodingSpecificOperations();
     address = R[n];
     AArch32.SetExclusiveMonitors(address, 4);
     R[t] = MemO[address, 4];
 

.SS Assembler Symbols

 <c>
  See Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <Rt>
  Encoded in Rt
  Is the general-purpose register to be transferred, encoded in the "Rt" field.

 <Rn>
  Encoded in Rn
  Is the general-purpose base register, encoded in the "Rn" field.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();
     address = R[n];
     AArch32.SetExclusiveMonitors(address, 4);
     R[t] = MemO[address, 4];


.SS Operational Notes

 
 If CPSR.DIT is 1, the timing of this instruction is insensitive to the value of the data being loaded or stored.
