.nh
.TH "LDREXH -- AArch32" "7" " "  "instruction" "general"
.SS LDREXH
 Load Register Exclusive Halfword

 Load Register Exclusive Halfword derives an address from a base register value,
 loads a halfword from memory, zero-extends it to form a 32-bit word, writes it
 to a register and:


 For more information about support for shared memory see Synchronization and
 semaphores. For information about memory accesses see Memory accesses.

 For more information about the constrained unpredictable behavior of this
 instruction, see Architectural Constraints on UNPREDICTABLE behaviors.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                                                   
                                             10                    
                         20                11 |                    
         28        23  21 |      16      12 | | 9 8       4       0
          |         |   | |       |       | | | | |       |       |
  |. . . .|0 0 0 1 1|1 1|1|. . . .|. . . .|1|1|1|1|1 0 0 1|1 1 1 1|
  |                 |   | |       |           | |         |
  `-cond(!= 1111)   |   | `-Rn    `-Rt        | `-ord     `-xRt
                    |   `-L                   `-ex
                    `-size
  
  
 
.SS A1
 
 LDREXH{<c>}{<q>} <Rt>, [<Rn>]
 
 t = UInt(Rt);  n = UInt(Rn);
 if t == 15 || n == 15 then UNPREDICTABLE;
.SS T1 - T32
 
                                                                   
                                                                   
                         05                                        
                       06 |      01      12       8   6   4       0
                        | |       |       |       |   |   |       |
   1 1 1 0 1 0 0 0 1 1 0|1|. . . .|. . . .|1 1 1 1|0 1|0 1|1 1 1 1|
                        | |       |       |           |   |
                        | `-Rn    `-Rt    `-Rt2       |   `-Rd
                        `-L                           `-sz
  
  
 
.SS T1
 
 LDREXH{<c>}{<q>} <Rt>, [<Rn>]
 
 t = UInt(Rt);  n = UInt(Rn);
 if t == 15 || n == 15 then UNPREDICTABLE; // Armv8-A removes UNPREDICTABLE for R13
 
 if ConditionPassed() then
     EncodingSpecificOperations();
     address = R[n];
     AArch32.SetExclusiveMonitors(address,2);
     R[t] = ZeroExtend(MemA[address,2], 32);
 

.SS Assembler Symbols

 <c>
  See Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <Rt>
  Encoded in Rt
  Is the general-purpose register to be transferred, encoded in the "Rt" field.

 <Rn>
  Encoded in Rn
  Is the general-purpose base register, encoded in the "Rn" field.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();
     address = R[n];
     AArch32.SetExclusiveMonitors(address,2);
     R[t] = ZeroExtend(MemA[address,2], 32);


.SS Operational Notes

 
 If CPSR.DIT is 1, the timing of this instruction is insensitive to the value of the data being loaded or stored.
