.nh
.TH "CSDB -- AArch32" "7" " "  "instruction" "general"
.SS CSDB
 Consumption of Speculative Data Barrier

 Consumption of Speculative Data Barrier is a memory barrier that controls
 speculative execution and data value prediction.

 No instruction other than branch instructions and instructions that write to
 the PC appearing in program order after the CSDB can be speculatively executed
 using the results of any:


 For more information about the constrained unpredictable behavior, see
 Architectural Constraints on UNPREDICTABLE behaviors.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                       13                          
                                     14 |                          
                     22            15 | |                          
         28        23 |  20      16 | | |12                       0
          |         | |   |       | | | | |                       |
  |. . . .|0 0 1 1 0|0|1 0|0 0 0 0|1|1|1|1|0 0 0 0 0 0 0 1 0 1 0 0|
  |                 |     |               |
  `-cond(!= 1111)   `-R   `-imm4          `-imm12
  
  
 
.SS A1
 
 CSDB{<c>}{<q>}
 
 if cond != '1110' then UNPREDICTABLE;      // CSDB must be encoded with AL condition
.SS T1 - T32
 
                               02          11                      
                             03 |        12 |                      
                           04 | |      13 | |                      
                         05 | | |01  14 | | |     8       4       0
                          | | | | |   | | | |     |       |       |
   1 1 1 1 0 0 1 1 1 0 1 0|1|1|1|1|1 0|0|0|0|0 0 0|0 0 0 1|0 1 0 0|
                                                  |       |
                                                  `-hint  `-option
  
  
 
.SS T1
 
 CSDB{<c>}.W
 
 if InITBlock() then UNPREDICTABLE;
 
 if ConditionPassed() then
     EncodingSpecificOperations();
 
     ConsumptionOfSpeculativeDataBarrier();
 

.SS Assembler Symbols

 <c>
  See Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();
 
     ConsumptionOfSpeculativeDataBarrier();

