.nh
.TH "DUP (scalar)" "7" " "  "instruction" "sve"
.SS DUP (scalar)
 Broadcast general-purpose register to vector elements (unpredicated)

 Unconditionally broadcast the general-purpose scalar source register into each
 element of the destination vector. This instruction is unpredicated.

 Status : Green

 Predicated : False

 takes_pred_movprfx : False



.SS SVE - A64 - dup_z_r_
 
                                                                   
                                                                   
                                                                   
                 24  22                      10         5         0
                  |   |                       |         |         |
   0 0 0 0 0 1 0 1|. .|1 0 0 0 0 0 0 0 1 1 1 0|. . . . .|. . . . .|
                  |                           |         |
                  `-size                      `-Rn      `-Zd
  
  
 
.SS SVE
 
 DUP     <Zd>.<T>, <R><n|SP>
 
 if !HaveSVE() then UNDEFINED;
 integer esize = 8 << UInt(size);
 integer n = UInt(Rn);
 integer d = UInt(Zd);
 
 CheckSVEEnabled();
 integer elements = VL DIV esize;
 bits(64) operand;
 if n == 31 then
     operand = SP[];
 else
     operand = X[n];
 bits(VL) result;
 
 for e = 0 to elements-1
     Elem[result, e, esize] = operand<esize-1:0>;
 
 Z[d] = result;
 

.SS Assembler Symbols

 <Zd>
  Encoded in Zd
  Is the name of the destination scalable vector register, encoded in the "Zd"
  field.

 <T>
  Encoded in size
  Is the size specifier,

  size <T> 
  00   B   
  01   H   
  10   S   
  11   D   

 <R>
  Encoded in size
  Is a width specifier,

  size <R> 
  01   W   
  x0   W   
  11   X   

 <n|SP>
  Encoded in Rn
  Is the number [0-30] of the general-purpose source register or the name SP
  (31), encoded in the "Rn" field.



.SS Operation

 CheckSVEEnabled();
 integer elements = VL DIV esize;
 bits(64) operand;
 if n == 31 then
     operand = SP[];
 else
     operand = X[n];
 bits(VL) result;
 
 for e = 0 to elements-1
     Elem[result, e, esize] = operand<esize-1:0>;
 
 Z[d] = result;

