.nh
.TH "RDFFR, RDFFRS (predicated)" "7" " "  "instruction" "sve"
.SS RDFFR, RDFFRS (predicated)
 Return predicate of succesfully loaded elements

 Read the first-fault register (FFR) and place active elements in the
 corresponding elements of the destination predicate. Inactive elements in the
 destination predicate register are set to zero. Optionally sets the First (N),
 None (Z), !Last (C) condition flags based on the predicate result, and the V
 flag to zero.

 Status : Green

 Predicated : True

 takes_pred_movprfx : False


It has encodings from 2 classes: Not setting the condition flags and Setting the condition flags

.SS Not setting the condition flags - A64 - rdffr_p_p_f_
 
                                                                   
                     22                                            
                   23 |                                            
                 24 | |                      10 9       5 4       0
                  | | |                       | |       | |       |
   0 0 1 0 0 1 0 1|0|0|0 1 1 0 0 0 1 1 1 1 0 0|0|. . . .|0|. . . .|
                  | |                           |         |
                  | `-S                         `-Pg      `-Pd
                  `-op
  
  
 
.SS Not setting the condition flags
 
 RDFFR   <Pd>.B, <Pg>/Z
 
 if !HaveSVE() then UNDEFINED;
 integer g = UInt(Pg);
 integer d = UInt(Pd);
 boolean setflags = FALSE;
.SS Setting the condition flags - A64 - rdffrs_p_p_f_
 
                                                                   
                     22                                            
                   23 |                                            
                 24 | |                      10 9       5 4       0
                  | | |                       | |       | |       |
   0 0 1 0 0 1 0 1|0|1|0 1 1 0 0 0 1 1 1 1 0 0|0|. . . .|0|. . . .|
                  | |                           |         |
                  | `-S                         `-Pg      `-Pd
                  `-op
  
  
 
.SS Setting the condition flags
 
 RDFFRS  <Pd>.B, <Pg>/Z
 
 if !HaveSVE() then UNDEFINED;
 integer g = UInt(Pg);
 integer d = UInt(Pd);
 boolean setflags = TRUE;
 
 CheckSVEEnabled();
 bits(PL) mask = P[g];
 bits(PL) ffr = FFR[];
 bits(PL) result = ffr AND mask;
 
 if setflags then
     PSTATE.<N,Z,C,V> = PredTest(mask, result, 8);
 P[d] = result;
 

.SS Assembler Symbols

 <Pd>
  Encoded in Pd
  Is the name of the destination scalable predicate register, encoded in the
  "Pd" field.

 <Pg>
  Encoded in Pg
  Is the name of the governing scalable predicate register, encoded in the "Pg"
  field.



.SS Operation

 CheckSVEEnabled();
 bits(PL) mask = P[g];
 bits(PL) ffr = FFR[];
 bits(PL) result = ffr AND mask;
 
 if setflags then
     PSTATE.<N,Z,C,V> = PredTest(mask, result, 8);
 P[d] = result;

