.nh
.TH "DECP (scalar)" "7" " "  "instruction" "sve"
.SS DECP (scalar)
 Decrement scalar by count of true predicate elements

 Counts the number of true elements in the source predicate and then uses the
 result to decrement the scalar destination.

 Status : Green

 Predicated : False

 takes_pred_movprfx : False



.SS SVE - A64 - decp_r_p_r_
 
                                                                   
                                 16                                
                               17 |          10                    
                 24  22      18 | |        11 | 9       5         0
                  |   |       | | |         | | |       |         |
   0 0 1 0 0 1 0 1|. .|1 0 1 1|0|1|1 0 0 0 1|0|0|. . . .|. . . . .|
                  |           | |           | | |       |
                  `-size      | `-D         | | `-Pm    `-Rdn
                              `-op          | `-opc2<0>
                                            `-opc2<1>
  
  
 
.SS SVE
 
 DECP    <Xdn>, <Pm>.<T>
 
 if !HaveSVE() then UNDEFINED;
 integer esize = 8 << UInt(size);
 integer m = UInt(Pm);
 integer dn = UInt(Rdn);
 
 CheckSVEEnabled();
 integer elements = VL DIV esize;
 bits(64) operand1 = X[dn];
 bits(PL) operand2 = P[m];
 integer count = 0;
 
 for e = 0 to elements-1
     if ElemP[operand2, e, esize] == '1' then
         count = count + 1;
 
 X[dn] = operand1 - count;
 

.SS Assembler Symbols

 <Xdn>
  Encoded in Rdn
  Is the 64-bit name of the source and destination general-purpose register,
  encoded in the "Rdn" field.

 <Pm>
  Encoded in Pm
  Is the name of the source scalable predicate register, encoded in the "Pm"
  field.

 <T>
  Encoded in size
  Is the size specifier,

  size <T> 
  00   B   
  01   H   
  10   S   
  11   D   



.SS Operation

 CheckSVEEnabled();
 integer elements = VL DIV esize;
 bits(64) operand1 = X[dn];
 bits(PL) operand2 = P[m];
 integer count = 0;
 
 for e = 0 to elements-1
     if ElemP[operand2, e, esize] == '1' then
         count = count + 1;
 
 X[dn] = operand1 - count;

