.nh
.TH "FCMLT (vectors)" "7" " "  "alias" "sve"
.SS FCMLT (vectors)
 FCMLT is an alias of FCMGT

 Floating-point compare less than vector

 Compare active floating-point elements in the first source vector being less
 than corresponding elements in the second source vector, and place the boolean
 results of the comparison in the corresponding elements of the destination
 predicate. Inactive elements in the destination predicate register are set to
 zero. Does not set the condition flags.

 Status : Green

 Predicated : True

 takes_pred_movprfx : False



.SS Greater than - A64 - fcmgt_p_p_zz_
 
                                       13                          
                                     14 |                          
                       21          15 | |                          
                 24  22 |        16 | | |    10         5 4       0
                  |   | |         | | | |     |         | |       |
   0 1 1 0 0 1 0 1|. .|0|. . . . .|0|1|0|. . .|. . . . .|1|. . . .|
                  |     |         |   | |     |         | |
                  |     `-Zm      |   | `-Pg  `-Zn      | `-Pd
                  `-size          |   `-cmph            `-cmpl
                                  `-op
  
  
 
.SS Greater than
 
 FCMLT   <Pd>.<T>, <Pg>/Z, <Zm>.<T>, <Zn>.<T>
 
 FCMGT   <Pd>.<T>, <Pg>/Z, <Zn>.<T>, <Zm>.<T>
 

.SS Assembler Symbols

 <Pd>
  Encoded in Pd
  Is the name of the destination scalable predicate register, encoded in the
  "Pd" field.

 <Zm>
  Encoded in Zm
  Is the name of the second source scalable vector register, encoded in the "Zm"
  field.

 <Zn>
  Encoded in Zn
  Is the name of the first source scalable vector register, encoded in the "Zn"
  field.

 <T>
  Encoded in size
  Is the size specifier,

  size <T>      
  00   RESERVED 
  01   H        
  10   S        
  11   D        

 <Pg>
  Encoded in Pg
  Is the name of the governing scalable predicate register P0-P7, encoded in the
  "Pg" field.



.SS Operation

 The manual of FCMGT gives pseudocode for FCMLT.
