.nh
.TH "MOV (vector) -- A64" "7" " "  "alias" "advsimd"
.SS MOV (vector)
 MOV is an alias of ORR

 Move vector

 Move vector. This instruction copies the vector in the source SIMD&FP register
 into the destination SIMD&FP register.

 Depending on the settings in the CPACR_EL1, CPTR_EL2, and CPTR_EL3 registers,
 and the current Security state and Exception level, an attempt to execute the
 instruction might be trapped.



.SS Three registers of the same type - A64 - ORR_asimdsame_only
 
                                                                   
       29                                                          
     30 |              21                    10                    
   31 | |        24  22 |        16        11 |         5         0
    | | |         |   | |         |         | |         |         |
   0|.|0|0 1 1 1 0|1 0|1|. . . . .|0 0 0 1 1|1|. . . . .|. . . . .|
    | |           |     |         |           |         |
    | `-U         |     `-Rm      `-opcode    `-Rn      `-Rd
    `-Q           `-size
  
  
 
.SS Three registers of the same type
 
 MOV  <Vd>.<T>, <Vn>.<T>
 
 ORR  <Vd>.<T>, <Vn>.<T>, <Vn>.<T>
 

.SS Assembler Symbols

 <Vd>
  Encoded in Rd
  Is the name of the SIMD&FP destination register, encoded in the "Rd" field.

 <T>
  Encoded in Q
  Is an arrangement specifier,

  Q <T> 
  0 8B  
  1 16B 

 <Vn>
  Encoded in Rn
  Is the name of the first SIMD&FP source register, encoded in the "Rn" field.



.SS Operation

 The manual of ORR gives pseudocode for MOV.

.SS Operational Notes

 
 If PSTATE.DIT is 1: 
 
 The execution time of this instruction is independent of: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
 The response of this instruction to asynchronous exceptions does not vary based on: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
