.nh
.TH "VMLA (integer) -- AArch32" "7" " "  "instruction" "fpsimd"
.SS VMLA (integer)
 Vector Multiply Accumulate (integer)

 Vector Multiply Accumulate multiplies corresponding elements in two vectors,
 and adds the products to the corresponding elements of the destination vector.

 Depending on settings in the CPACR, NSACR, and HCPTR registers, and the
 Security state and PE mode in which the instruction is executed, an attempt to
 execute the instruction might be undefined, or trapped to Hyp mode. For more
 information see Enabling Advanced SIMD and floating-point support.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                     22                                            
                   23 |                                            
                 24 | |                                            
               25 | | |  20      16      12       8 7 6 5 4       0
                | | | |   |       |       |       | | | | |       |
   1 1 1 1 0 0 1|0|0|.|. .|. . . .|. . . .|1 0 0 1|.|.|.|0|. . . .|
                |   | |   |       |       |       | | | | |
                |   | |   `-Vn    `-Vd    `-opc   | | | | `-Vm
                |   | `-size                      | | | `-o1
                |   `-D                           | | `-M
                `-op                              | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VMLA{<c>}{<q>}.<type><size> <Dd>, <Dn>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VMLA{<c>}{<q>}.<type><size> <Qd>, <Qn>, <Qm>
 
 if size == '11' then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vn<0> == '1' || Vm<0> == '1') then UNDEFINED;
 add = (op == '0');  long_destination = FALSE;
 unsigned = FALSE;  // "Don't care" value: TRUE produces same functionality
 esize = 8 << UInt(size);  elements = 64 DIV esize;
 d = UInt(D:Vd);  n = UInt(N:Vn);  m = UInt(M:Vm);  regs = if Q == '0' then 1 else 2;
.SS T1 - T32
 
                                                                   
                                                                   
         13          07                                            
       14 |        08 |  05      01      12       8 7 6 5 4       0
        | |         | |   |       |       |       | | | | |       |
   1 1 1|0|1 1 1 1 0|.|. .|. . . .|. . . .|1 0 0 1|.|.|.|0|. . . .|
        |           | |   |       |       |       | | | | |
        `-op        | |   `-Vn    `-Vd    `-opc   | | | | `-Vm
                    | `-size                      | | | `-o1
                    `-D                           | | `-M
                                                  | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VMLA{<c>}{<q>}.<type><size> <Dd>, <Dn>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VMLA{<c>}{<q>}.<type><size> <Qd>, <Qn>, <Qm>
 
 if size == '11' then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vn<0> == '1' || Vm<0> == '1') then UNDEFINED;
 add = (op == '0');  long_destination = FALSE;
 unsigned = FALSE;  // "Don't care" value: TRUE produces same functionality
 esize = 8 << UInt(size);  elements = 64 DIV esize;
 d = UInt(D:Vd);  n = UInt(N:Vn);  m = UInt(M:Vm);  regs = if Q == '0' then 1 else 2;
 
 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     for r = 0 to regs-1
         for e = 0 to elements-1
             product = Int(Elem[Din[n+r],e,esize],unsigned) * Int(Elem[Din[m+r],e,esize],unsigned);
             addend = if add then product else -product;
             if long_destination then
                 Elem[Q[d>>1],e,2*esize] = Elem[Qin[d>>1],e,2*esize] + addend;
             else
                 Elem[D[d+r],e,esize] = Elem[Din[d+r],e,esize] + addend;
 

.SS Assembler Symbols

 <c>
  For encoding A1: see Standard assembler syntax fields. This encoding must be
  unconditional.

 <c>
  For encoding T1: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <type>
  The data type for the elements of the operands. It must be one of:
  SOptional in encoding T1/A1. Encoded as U = 0 in encoding T2/A2.
  UOptional in encoding T1/A1. Encoded as U = 1 in encoding T2/A2.
  IAvailable only in encoding T1/A1.

 <size>
  The data size for the elements of the operands. It must be one of:
  8Encoded as size = 0b00.                                         16Encoded as
  size = 0b01.                                         32Encoded as size = 0b10.

 <Qd>
  Encoded in D:Vd
  Is the 128-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field as <Qd>*2.

 <Qn>
  Encoded in N:Vn
  Is the 128-bit name of the first SIMD&FP source register, encoded in the
  "N:Vn" field as <Qn>*2.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the second SIMD&FP source register, encoded in the
  "M:Vm" field as <Qm>*2.

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.

 <Dn>
  Encoded in N:Vn
  Is the 64-bit name of the first SIMD&FP source register, encoded in the "N:Vn"
  field.

 <Dm>
  Encoded in M:Vm
  Is the 64-bit name of the second SIMD&FP source register, encoded in the
  "M:Vm" field.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     for r = 0 to regs-1
         for e = 0 to elements-1
             product = Int(Elem[Din[n+r],e,esize],unsigned) * Int(Elem[Din[m+r],e,esize],unsigned);
             addend = if add then product else -product;
             if long_destination then
                 Elem[Q[d>>1],e,2*esize] = Elem[Qin[d>>1],e,2*esize] + addend;
             else
                 Elem[D[d+r],e,esize] = Elem[Din[d+r],e,esize] + addend;


.SS Operational Notes

 
 If CPSR.DIT is 1 and this instruction passes its condition execution check: 
 
 The execution time of this instruction is independent of: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
 The response of this instruction to asynchronous exceptions does not vary based on: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
