.nh
.TH "VZIP -- AArch32" "7" " "  "instruction" "fpsimd"
.SS VZIP
 Vector Zip

 Vector Zip interleaves the elements of two vectors.

 The elements of the vectors can be 8-bit, 16-bit, or 32-bit. There is no
 distinction between data types.





 Depending on settings in the CPACR, NSACR, and HCPTR registers, and the
 Security state and PE mode in which the instruction is executed, an attempt to
 execute the instruction might be undefined, or trapped to Hyp mode. For more
 information see Enabling Advanced SIMD and floating-point support.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                                                   
                                                                   
                     22                    11                      
                   23 |  20  18  16      12 |       7 6 5 4       0
                    | |   |   |   |       | |       | | | |       |
   1 1 1 1 0 0 1 1 1|.|1 1|. .|1 0|. . . .|0|0 0 1 1|.|.|0|. . . .|
                    |     |   |   |         |       | |   |
                    `-D   |   |   `-Vd      `-opc2  | `-M `-Vm
                          |   `-opc1                `-Q
                          `-size
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VZIP{<c>}{<q>}.<dt> <Dd>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VZIP{<c>}{<q>}.<dt> <Qd>, <Qm>
 
 if size == '11' || (Q == '0' && size == '10') then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vm<0> == '1') then UNDEFINED;
 quadword_operation = (Q == '1');  esize = 8 << UInt(size);
 d = UInt(D:Vd);  m = UInt(M:Vm);
.SS T1 - T32
 
                                                                   
                                                                   
                     07                    11                      
                   08 |  05  03  01      12 |       7 6 5 4       0
                    | |   |   |   |       | |       | | | |       |
   1 1 1 1 1 1 1 1 1|.|1 1|. .|1 0|. . . .|0|0 0 1 1|.|.|0|. . . .|
                    |     |   |   |         |       | |   |
                    `-D   |   |   `-Vd      `-opc2  | `-M `-Vm
                          |   `-opc1                `-Q
                          `-size
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VZIP{<c>}{<q>}.<dt> <Dd>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VZIP{<c>}{<q>}.<dt> <Qd>, <Qm>
 
 if size == '11' || (Q == '0' && size == '10') then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vm<0> == '1') then UNDEFINED;
 quadword_operation = (Q == '1');  esize = 8 << UInt(size);
 d = UInt(D:Vd);  m = UInt(M:Vm);
 
 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     if quadword_operation then
         if d == m then
             Q[d>>1] = bits(128) UNKNOWN;  Q[m>>1] = bits(128) UNKNOWN;
         else
             bits(256) zipped_q;
             for e = 0 to (128 DIV esize) - 1
                 Elem[zipped_q,2*e,esize] = Elem[Q[d>>1],e,esize];
                 Elem[zipped_q,2*e+1,esize] = Elem[Q[m>>1],e,esize];
             Q[d>>1] = zipped_q<127:0>;  Q[m>>1] = zipped_q<255:128>;
     else
         if d == m then
             D[d] = bits(64) UNKNOWN;  D[m] = bits(64) UNKNOWN;
         else
             bits(128) zipped_d;
             for e = 0 to (64 DIV esize) - 1
                 Elem[zipped_d,2*e,esize] = Elem[D[d],e,esize];
                 Elem[zipped_d,2*e+1,esize] = Elem[D[m],e,esize];
             D[d] = zipped_d<63:0>;  D[m] = zipped_d<127:64>;
 

.SS Assembler Symbols

 <c>
  For encoding A1: see Standard assembler syntax fields. This encoding must be
  unconditional.

 <c>
  For encoding T1: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <dt>
  Encoded in size
  For the 64-bit SIMD vector variant: is the data type for the elements of the
  vectors,

  size <dt>     
  00   8        
  01   16       
  1x   RESERVED 

 <dt>
  Encoded in size
  For the 128-bit SIMD vector variant: is the data type for the elements of the
  vectors,

  size <dt>     
  00   8        
  01   16       
  10   32       
  11   RESERVED 

 <Qd>
  Encoded in D:Vd
  Is the 128-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field as <Qd>*2.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the SIMD&FP source register, encoded in the "M:Vm"
  field as <Qm>*2.

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.

 <Dm>
  Encoded in M:Vm
  Is the 64-bit name of the SIMD&FP source register, encoded in the "M:Vm"
  field.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     if quadword_operation then
         if d == m then
             Q[d>>1] = bits(128) UNKNOWN;  Q[m>>1] = bits(128) UNKNOWN;
         else
             bits(256) zipped_q;
             for e = 0 to (128 DIV esize) - 1
                 Elem[zipped_q,2*e,esize] = Elem[Q[d>>1],e,esize];
                 Elem[zipped_q,2*e+1,esize] = Elem[Q[m>>1],e,esize];
             Q[d>>1] = zipped_q<127:0>;  Q[m>>1] = zipped_q<255:128>;
     else
         if d == m then
             D[d] = bits(64) UNKNOWN;  D[m] = bits(64) UNKNOWN;
         else
             bits(128) zipped_d;
             for e = 0 to (64 DIV esize) - 1
                 Elem[zipped_d,2*e,esize] = Elem[D[d],e,esize];
                 Elem[zipped_d,2*e+1,esize] = Elem[D[m],e,esize];
             D[d] = zipped_d<63:0>;  D[m] = zipped_d<127:64>;


.SS Operational Notes

 
 If CPSR.DIT is 1 and this instruction passes its condition execution check: 
 
 The execution time of this instruction is independent of: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
 The response of this instruction to asynchronous exceptions does not vary based on: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
