.nh
.TH "VCLE (register) -- AArch32" "7" " "  "alias" "fpsimd"
.SS VCLE (register)
 VCLE is an alias of VCGE

 Vector Compare Less Than or Equal


It has encodings from the following instruction sets:  A32 (A1 and A2) and  T32 (T1 and T2).

.SS A1 - A32
 
                     22                                            
                   23 |                                            
                 24 | |                                            
               25 | | |  20      16      12       8 7 6 5 4       0
                | | | |   |       |       |       | | | | |       |
   1 1 1 1 0 0 1|.|0|.|. .|. . . .|. . . .|0 0 1 1|.|.|.|1|. . . .|
                |   | |   |       |       |       | | | | |
                `-U | |   `-Vn    `-Vd    `-opc   | | | | `-Vm
                    | `-size                      | | | `-o1
                    `-D                           | | `-M
                                                  | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VCLE{<c>}{<q>}.<dt> {<Dd>, }<Dn>, <Dm>
 
 VCGE{<c>}{<q>}.<dt> <Dd>, <Dm>, <Dn>
.SS 128-bit SIMD vector(Q == 1)
 
 VCLE{<c>}{<q>}.<dt> {<Qd>, }<Qn>, <Qm>
 
 VCGE{<c>}{<q>}.<dt> <Qd>, <Qm>, <Qn>
.SS A2 - A32
 
                     22                                            
                   23 |                                            
                 24 | |  20                                        
               25 | | |21 |      16      12       8 7 6 5 4       0
                | | | | | |       |       |       | | | | |       |
   1 1 1 1 0 0 1|1|0|.|0|.|. . . .|. . . .|1 1 1 0|.|.|.|0|. . . .|
                |   |   | |       |       |       | | | | |
                `-U `-D | `-Vn    `-Vd    `-opc   | | | | `-Vm
                        `-sz                      | | | `-o1
                                                  | | `-M
                                                  | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VCLE{<c>}{<q>}.<dt> {<Dd>, }<Dn>, <Dm>
 
 VCGE{<c>}{<q>}.<dt> <Dd>, <Dm>, <Dn>
.SS 128-bit SIMD vector(Q == 1)
 
 VCLE{<c>}{<q>}.<dt> {<Qd>, }<Qn>, <Qm>
 
 VCGE{<c>}{<q>}.<dt> <Qd>, <Qm>, <Qn>
.SS T1 - T32
 
                                                                   
                                                                   
         13          07                                            
       14 |        08 |  05      01      12       8 7 6 5 4       0
        | |         | |   |       |       |       | | | | |       |
   1 1 1|.|1 1 1 1 0|.|. .|. . . .|. . . .|0 0 1 1|.|.|.|1|. . . .|
        |           | |   |       |       |       | | | | |
        `-U         | |   `-Vn    `-Vd    `-opc   | | | | `-Vm
                    | `-size                      | | | `-o1
                    `-D                           | | `-M
                                                  | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VCLE{<c>}{<q>}.<dt> {<Dd>, }<Dn>, <Dm>
 
 VCGE{<c>}{<q>}.<dt> <Dd>, <Dm>, <Dn>
.SS 128-bit SIMD vector(Q == 1)
 
 VCLE{<c>}{<q>}.<dt> {<Qd>, }<Qn>, <Qm>
 
 VCGE{<c>}{<q>}.<dt> <Qd>, <Qm>, <Qn>
.SS T2 - T32
 
                         05                                        
                       06 |                                        
         13          07 | |                                        
       14 |        08 | | |      01      12       8 7 6 5 4       0
        | |         | | | |       |       |       | | | | |       |
   1 1 1|1|1 1 1 1 0|.|0|.|. . . .|. . . .|1 1 1 0|.|.|.|0|. . . .|
        |           |   | |       |       |       | | | | |
        `-U         `-D | `-Vn    `-Vd    `-opc   | | | | `-Vm
                        `-sz                      | | | `-o1
                                                  | | `-M
                                                  | `-Q
                                                  `-N
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VCLE{<c>}{<q>}.<dt> {<Dd>, }<Dn>, <Dm>
 
 VCGE{<c>}{<q>}.<dt> <Dd>, <Dm>, <Dn>
.SS 128-bit SIMD vector(Q == 1)
 
 VCLE{<c>}{<q>}.<dt> {<Qd>, }<Qn>, <Qm>
 
 VCGE{<c>}{<q>}.<dt> <Qd>, <Qm>, <Qn>
 

.SS Assembler Symbols

 <Dm>
  Encoded in M:Vm
  Is the 64-bit name of the second SIMD&FP source register, encoded in the
  "M:Vm" field.

 <Dn>
  Encoded in N:Vn
  Is the 64-bit name of the first SIMD&FP source register, encoded in the "N:Vn"
  field.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the second SIMD&FP source register, encoded in the
  "M:Vm" field as <Qm>*2.

 <Qn>
  Encoded in N:Vn
  Is the 128-bit name of the first SIMD&FP source register, encoded in the
  "N:Vn" field as <Qn>*2.

 <c>
  For encoding A1 and A2: see Standard assembler syntax fields. This encoding
  must be unconditional.

 <c>
  For encoding T1 and T2: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <dt>
  Encoded in U:size
  For encoding A1 and T1: is the data type for the elements of the operands,

  U size <dt> 
  0 00   S8   
  0 01   S16  
  0 10   S32  
  1 00   U8   
  1 01   U16  
  1 10   U32  

 <dt>
  Encoded in sz
  For encoding A2 and T2: is the data type for the elements of the vectors,

  sz <dt> 
  0  F32  
  1  F16  

 <Qd>
  Encoded in D:Vd
  Is the 128-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field as <Qd>*2.

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.



.SS Operation

 The manual of VCGE gives pseudocode for VCLE.
