.nh
.TH "VSUBHN -- AArch32" "7" " "  "instruction" "fpsimd"
.SS VSUBHN
 Vector Subtract and Narrow, returning High Half

 Vector Subtract and Narrow, returning High Half subtracts the elements of one
 quadword vector from the corresponding elements of another quadword vector,
 takes the most significant half of each result, and places the final results in
 a doubleword vector. The results are truncated. For rounded results, see
 VRSUBHN.

 There is no distinction between signed and unsigned integers.

 Depending on settings in the CPACR, NSACR, and HCPTR registers, and the
 Security state and PE mode in which the instruction is executed, an attempt to
 execute the instruction might be undefined, or trapped to Hyp mode. For more
 information see Enabling Advanced SIMD and floating-point support.

 Related encodings: See Advanced SIMD data-processing for the T32 instruction
 set, or Advanced SIMD data-processing for the A32 instruction set.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                     22                                            
                   23 |                                            
                 24 | |                                            
               25 | | |  20      16      12       8 7 6 5 4       0
                | | | |   |       |       |       | | | | |       |
   1 1 1 1 0 0 1|0|1|.|. .|. . . .|. . . .|0 1 1 0|.|0|.|0|. . . .|
                |   | |   |       |       |       |   |   |
                `-U | |   `-Vn    `-Vd    `-opc   `-N `-M `-Vm
                    | `-size(!= 11)
                    `-D
  
  
 
.SS A1
 
 VSUBHN{<c>}{<q>}.<dt> <Dd>, <Qn>, <Qm>
 
 if size == '11' then SEE "Related encodings";
 if Vn<0> == '1' || Vm<0> == '1' then UNDEFINED;
 esize = 8 << UInt(size);  elements = 64 DIV esize;
 d = UInt(D:Vd);  n = UInt(N:Vn);  m = UInt(M:Vm);
.SS T1 - T32
 
                                                                   
                                                                   
         13          07                                            
       14 |        08 |  05      01      12       8 7 6 5 4       0
        | |         | |   |       |       |       | | | | |       |
   1 1 1|0|1 1 1 1 1|.|. .|. . . .|. . . .|0 1 1 0|.|0|.|0|. . . .|
        |           | |   |       |       |       |   |   |
        `-U         | |   `-Vn    `-Vd    `-opc   `-N `-M `-Vm
                    | `-size(!= 11)
                    `-D
  
  
 
.SS T1
 
 VSUBHN{<c>}{<q>}.<dt> <Dd>, <Qn>, <Qm>
 
 if size == '11' then SEE "Related encodings";
 if Vn<0> == '1' || Vm<0> == '1' then UNDEFINED;
 esize = 8 << UInt(size);  elements = 64 DIV esize;
 d = UInt(D:Vd);  n = UInt(N:Vn);  m = UInt(M:Vm);
 
 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     for e = 0 to elements-1
         result = Elem[Qin[n>>1],e,2*esize] - Elem[Qin[m>>1],e,2*esize];
         Elem[D[d],e,esize] = result<2*esize-1:esize>;
 

.SS Assembler Symbols

 <c>
  For encoding A1: see Standard assembler syntax fields. This encoding must be
  unconditional.

 <c>
  For encoding T1: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <dt>
  Encoded in size
  Is the data type for the elements of the operands,

  size <dt> 
  00   I16  
  01   I32  
  10   I64  

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.

 <Qn>
  Encoded in N:Vn
  Is the 128-bit name of the first SIMD&FP source register, encoded in the
  "N:Vn" field as <Qn>*2.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the second SIMD&FP source register, encoded in the
  "M:Vm" field as <Qm>*2.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
     for e = 0 to elements-1
         result = Elem[Qin[n>>1],e,2*esize] - Elem[Qin[m>>1],e,2*esize];
         Elem[D[d],e,esize] = result<2*esize-1:esize>;


.SS Operational Notes

 
 If CPSR.DIT is 1 and this instruction passes its condition execution check: 
 
 The execution time of this instruction is independent of: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
 The response of this instruction to asynchronous exceptions does not vary based on: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
