.nh
.TH "VREV64 -- AArch32" "7" " "  "instruction" "fpsimd"
.SS VREV64
 Vector Reverse in doublewords

 Vector Reverse in doublewords reverses the order of 8-bit, 16-bit, or 32-bit
 elements in each doubleword of the vector, and places the result in the
 corresponding destination vector.

 There is no distinction between data types, other than size.



 Depending on settings in the CPACR, NSACR, and HCPTR registers, and the
 Security state and PE mode in which the instruction is executed, an attempt to
 execute the instruction might be undefined, or trapped to Hyp mode. For more
 information see Enabling Advanced SIMD and floating-point support.


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                                                   
                                                                   
                     22                    11                      
                   23 |  20  18  16      12 |   9   7 6 5 4       0
                    | |   |   |   |       | |   |   | | | |       |
   1 1 1 1 0 0 1 1 1|.|1 1|. .|0 0|. . . .|0|0 0|0 0|.|.|0|. . . .|
                    |     |   |   |             |   | |   |
                    `-D   |   |   `-Vd          |   | `-M `-Vm
                          |   `-opc1            |   `-Q
                          `-size                `-op
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VREV64{<c>}{<q>}.<dt> <Dd>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VREV64{<c>}{<q>}.<dt> <Qd>, <Qm>
 
 if UInt(op)+UInt(size) >= 3 then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vm<0> == '1') then UNDEFINED;
 
 esize = 8 << UInt(size);
 integer container_size;
 case op of
     when '10' container_size = 16;
     when '01' container_size = 32;
     when '00' container_size = 64;
 integer containers = 64 DIV container_size;
 integer elements_per_container = container_size DIV esize;
 
 d = UInt(D:Vd); m = UInt(M:Vm); regs = if Q == '0' then 1 else 2;
.SS T1 - T32
 
                                                                   
                                                                   
                     07                    11                      
                   08 |  05  03  01      12 |   9   7 6 5 4       0
                    | |   |   |   |       | |   |   | | | |       |
   1 1 1 1 1 1 1 1 1|.|1 1|. .|0 0|. . . .|0|0 0|0 0|.|.|0|. . . .|
                    |     |   |   |             |   | |   |
                    `-D   |   |   `-Vd          |   | `-M `-Vm
                          |   `-opc1            |   `-Q
                          `-size                `-op
  
  
 
.SS 64-bit SIMD vector(Q == 0)
 
 VREV64{<c>}{<q>}.<dt> <Dd>, <Dm>
.SS 128-bit SIMD vector(Q == 1)
 
 VREV64{<c>}{<q>}.<dt> <Qd>, <Qm>
 
 if UInt(op)+UInt(size) >= 3 then UNDEFINED;
 if Q == '1' && (Vd<0> == '1' || Vm<0> == '1') then UNDEFINED;
 
 esize = 8 << UInt(size);
 integer container_size;
 case op of
     when '10' container_size = 16;
     when '01' container_size = 32;
     when '00' container_size = 64;
 integer containers = 64 DIV container_size;
 integer elements_per_container = container_size DIV esize;
 
 d = UInt(D:Vd); m = UInt(M:Vm); regs = if Q == '0' then 1 else 2;
 
 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
 
     bits(64) result;
     integer element;
     integer rev_element;
     for r = 0 to regs-1
         element = 0;
         for c = 0 to containers-1
             rev_element = element + elements_per_container - 1;
             for e = 0 to elements_per_container-1
                 Elem[result, rev_element, esize] = Elem[D[m+r], element, esize];
                 element = element + 1;
                 rev_element = rev_element - 1;
         D[d+r] = result;
 

.SS Assembler Symbols

 <c>
  For encoding A1: see Standard assembler syntax fields. This encoding must be
  unconditional.

 <c>
  For encoding T1: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <dt>
  Encoded in size
  Is the data type for the elements of the operand,

  size <dt>     
  00   8        
  01   16       
  10   32       
  11   RESERVED 

 <Qd>
  Encoded in D:Vd
  Is the 128-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field as <Qd>*2.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the SIMD&FP source register, encoded in the "M:Vm"
  field as <Qm>*2.

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.

 <Dm>
  Encoded in M:Vm
  Is the 64-bit name of the SIMD&FP source register, encoded in the "M:Vm"
  field.



.SS Operation

 if ConditionPassed() then
     EncodingSpecificOperations();  CheckAdvSIMDEnabled();
 
     bits(64) result;
     integer element;
     integer rev_element;
     for r = 0 to regs-1
         element = 0;
         for c = 0 to containers-1
             rev_element = element + elements_per_container - 1;
             for e = 0 to elements_per_container-1
                 Elem[result, rev_element, esize] = Elem[D[m+r], element, esize];
                 element = element + 1;
                 rev_element = rev_element - 1;
         D[d+r] = result;


.SS Operational Notes

 
 If CPSR.DIT is 1 and this instruction passes its condition execution check: 
 
 The execution time of this instruction is independent of: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
 The response of this instruction to asynchronous exceptions does not vary based on: 
 The values of the data supplied in any of its registers.
 The values of the NZCV flags.
