.nh
.TH "VQSHRUN (zero) -- AArch32" "7" " "  "alias" "fpsimd"
.SS VQSHRUN (zero)
 VQSHRUN is an alias of VQMOVUN

 Vector Saturating Shift Right, Narrow


It has encodings from the following instruction sets:  A32 (A1) and  T32 (T1).

.SS A1 - A32
 
                                                                   
                                                                   
                     22                    11                      
                   23 |  20  18  16      12 |     8   6 5 4       0
                    | |   |   |   |       | |     |   | | |       |
   1 1 1 1 0 0 1 1 1|.|1 1|. .|1 0|. . . .|0|0 1 0|0 1|.|0|. . . .|
                    |     |   |   |               |   |   |
                    `-D   |   |   `-Vd            |   `-M `-Vm
                          |   `-opc1              `-op
                          `-size
  
  
 
.SS Unsigned result
 
 VQSHRUN{<c>}{<q>}.<dt> <Dd>, <Qm>, #0
 
 VQMOVUN{<c>}{<q>}.<dt> <Dd>, <Qm>
.SS T1 - T32
 
                                                                   
                                                                   
                     07                    11                      
                   08 |  05  03  01      12 |     8   6 5 4       0
                    | |   |   |   |       | |     |   | | |       |
   1 1 1 1 1 1 1 1 1|.|1 1|. .|1 0|. . . .|0|0 1 0|0 1|.|0|. . . .|
                    |     |   |   |               |   |   |
                    `-D   |   |   `-Vd            |   `-M `-Vm
                          |   `-opc1              `-op
                          `-size
  
  
 
.SS Unsigned result
 
 VQSHRUN{<c>}{<q>}.<dt> <Dd>, <Qm>, #0
 
 VQMOVUN{<c>}{<q>}.<dt> <Dd>, <Qm>
 

.SS Assembler Symbols

 <c>
  For encoding A1: see Standard assembler syntax fields. This encoding must be
  unconditional.

 <c>
  For encoding T1: see Standard assembler syntax fields.

 <q>
  See Standard assembler syntax fields.

 <dt>
  Encoded in size
  Is the data type for the elements of the operand,

  size <dt>     
  00   S16      
  01   S32      
  10   S64      
  11   RESERVED 

 <Dd>
  Encoded in D:Vd
  Is the 64-bit name of the SIMD&FP destination register, encoded in the "D:Vd"
  field.

 <Qm>
  Encoded in M:Vm
  Is the 128-bit name of the SIMD&FP source register, encoded in the "M:Vm"
  field as <Qm>*2.



.SS Operation

 The manual of VQMOVUN gives pseudocode for VQSHRUN.
